### ISSUE TITLE
Jit.ndi.receive ~ causing Max/MSP to crash to desktop when selecting different sources with Audio Engine on 

### ISSUE THREAD

**Issue by monobenji** [impsnldavid/jit.ndi#17] opened 2021-06-03 19:23 UTC
Hello,

I am on Mac OSX 10.15.7

I am crashing Max/MSP every time I switch NDI sources on the jit.NDI.receive~ object. I have tried both internal and external NDI sources and see the same result. This only occurs when the Max Audio engine is enabled, no stability issues when no audio passes. 

This is my first github post so please let me know what additonal information I can collect / submit to help diagnose. 

Thank you!

**Comment by pixsperdavid** [comment] 2021-06-07 09:37
Can you give details on the exact NDI sources you're testing with, the audio hardware/driver you're using and also your complete system specification. Does this crash occur when audio is not enabled?

**Comment by monobenji** [comment] 2021-06-07 21:44
Thank you for the quick response:

I am currently testing on a 2012 MacMini - 2.6Ghz i7 with only 4 GB of RAM.
Using CoreAudio as the audio driver, tried multiple different destinations
(all on CoreAudio). I have access to more powerful Macs if needed, might
take a day or two to get it hooked up in my office.

I only see this behavior when audio is enabled.  Stable for weeks at a time
with no audio enabled.

My original NDI sources are multiple Raspberry Pi 4B (8GB Ram) running
DiCaffeine NDI streamers. However after seeing the crash I tested with
another Mac streaming using jit.ndi.send~ and it showed the same behavior
regardless of source.

Thank you for looking into this!

Ps- I have been using your LXMax and imp.LTC externals for a few months and
they are both great! Thanks for writing such great software, I am a big fan.

**Comment by pixsperdavid** [comment] 2021-11-19 11:50
Fixed a audio-related crash whilst updating to NDI 5 which was likely the cause of this. Available in v0.3.0. Closing for now, please re-open if you still encounter this issue.

**Closed as completed by pixsperdavid** 2021-11-19 11:51 UTC
